apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-a60d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-a60d@sha256:5f3b20f4155d688a16d11150130ab5955c7ce6d2702c6894b247faa2c3070469
        name: my-nodejs
        resources: {}
status: {}
